### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by jedrekdomanski** [matenia/bootstrap-kaminari-views#19]
After installing the gems and applying `:theme => 'twitter-bootstrap-3'` it appears styled but after you click another page it reverts back to non-styled.
Steps to reproduce: install gems and apply the theme, refresh the page, the pagination style has changed, click on 2nd page and the style will disappear. I use `<%= paginate @posts, remote: true %>`

**Comment by goreilly** [comment]
did you put this in the application helper? It's working for me

```ruby
module ApplicationHelper

  # ...

  # Default pagination controls to use bootstrap theme
  def paginate(objects, options = {})
    options.reverse_merge!(theme: 'twitter-bootstrap-3')
    super(objects, options)
  end

end
```

If not you have to pass `:theme => 'twitter-bootstrap-3'` with each call to `paginate`

**Comment by jedrekdomanski** [comment]
I decided to style everything myself in css.
